### ISSUE TITLE
Can CRAN packages be used?

### ISSUE THREAD

**Issue by billdenney** [RichardHooijmaijers/nlmixr.docker#1]
Several of the packages installed from GitHub (vpc, n1qn1, and SnakeCharmR) are available on CRAN.  Is it feasible to install those from CRAN or is there a requirement (or major improvement) to install from GitHub?

**Comment by RichardHooijmaijers** [comment]
Not sure if the current CRAN versions of RxODE and nlmixr work only on the latest github versions or that CRAN can be used as well. I will discuss with Matt and if CRAN can be used, adapt the docker accordingly

**Comment by billdenney** [comment]
It may be worthwhile having a "development" and a "stable" build where "development" follows GitHub and "stable" either follows CRAN or uses a specific commit from GitHub.  My request is so that if I build the "stable" version today or tomorrow, I'll get the same image.

**Comment by billdenney** [comment]
I just tried to build the image, and I got the following error during installation of SnakeCharmR:

```
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘SnakeCharmR’ ...
** libs
g++  -I"/usr/local/lib/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/Rcp                                                     p/include" -I/usr/local/include   -fpic  -g -O2 -fstack-protector-strong -Wforma                                                     t -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp                                                      -o RcppExports.o
gcc -I"/usr/local/lib/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/Rcpp                                                     /include" -I/usr/local/include   -fpic  -g -O2 -fstack-protector-strong -Wformat                                                      -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.c -o init.o
g++  -I"/usr/local/lib/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/Rcp                                                     p/include" -I/usr/local/include   -fpic  -g -O2 -fstack-protector-strong -Wforma                                                     t -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c python.cpp -o p                                                     ython.o
python.cpp:4:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
/usr/local/lib/R/etc/Makeconf:168: recipe for target 'python.o' failed
```

I'm about to retry with the CRAN versions of everything feasible to get from CRAN.

**Comment by mattfidler** [comment]
If CRAN versions exist, they can now be used.  There was some lag between CRAN releaeses for various packages and what nlmixr was using.  I don't think that is the case any longer. 

Since you are having issues with `SnakeCharmR` you may have better traction with `reticulate`;  It seems that systems that work with `reticualte` don't seem to work with `SnakeCharmR`, though with docker I would think they would be the same.

**Comment by mattfidler** [comment]
Another point is you need python with sympy setup, in case that step wasn't done yet.  I have only ran the docker image, not built one before.

**Comment by billdenney** [comment]
`SnakeCharmR` is on CRAN, and the CRAN-based installation worked with it.

**Comment by billdenney** [comment]
sympy is installed via apt.

**Comment by RichardHooijmaijers** [comment]
It seems this issue can be closed. The new docker files were tested with the CRAN versions and work now

**Comment by mattfidler** [comment]
Hi @RichardHooijmaijers 

I would change SnakeCharmR to reticulate since this is a ubuntu system.  It runs faster than SnakeCharmR.  Windows seems to have some explainable problems with it currently.

**Comment by RichardHooijmaijers** [comment]
Hi @mattfidler, I updated both the docker files to use reticulate and pushed it to dockerhub and github
