### ISSUE TITLE
Remove nlmixr version 1 parts?

### ISSUE THREAD

**Issue by billdenney** [RichardHooijmaijers/nlmixr.docker#10]
I don't think that the original version of nlmixr (version 1) will install now.  Does it make sense to remove the `prod` and `dev` directories?

**Comment by RichardHooijmaijers** [comment]
It indeed makes more sense to focus on `nlmixr2` only. I have deleted the prod and dev folders and adjusted the readme accordingly. Also merged your latest PR into the main branch (thanks for this, makes it much easier to customize R package installation!)
