### ISSUE TITLE
pull access denied

### ISSUE THREAD

**Issue by PerOG7** [RichardHooijmaijers/nlmixr.docker#7]
I'm getting the following: 
docker: Error response from daemon: pull access denied for nlmixr2/nlmixr2prod, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Comment by PerOG7** [comment]
OK, I think the directory should be nlmixr, not nlmixr2 ?

**Comment by RichardHooijmaijers** [comment]
I think you are right! I have adapted the readme file accordingly, sorry for this
